### ISSUE TITLE
Update/create failing when using --setdefault

### ISSUE THREAD

**Issue by dosaki** [SmartBear/swaggerhub-cli#174]
### Q&A (please complete the following information)
 - CLI version: 0.2.13
 - OS: linux-x64 5.9.8-arch1-1
 - Node.js version: 15.2.0
 - SwaggerHub version if On-Premise: N/A

### Describe the bug you're encountering
When running `swaggerhub api:update username/api-name/XXX -f "/path/to/openapi.spec.json" --visibility=public --setdefault` or `swaggerhub api:create username/api-name/XXX -f "/path/to/openapi.spec.json" --visibility=public --setdefault`
I'm getting the following error:
```
Created version XXX of API 'username/api-name'
    TypeError: Cannot read property 'split' of undefined
```
The API does get created or updated but it isn't set to default.

The command works if I remove `--setdefault` so I don't think it's a problem with the api spec file.

### To reproduce...
1. Given I have an API set up at `username/api-name/XXX`
2. Execute either command:
    * `swaggerhub api:update username/api-name/XXX -f "/path/to/openapi.spec.json" --visibility=public --setdefault` (for an existing one)
    * `swaggerhub api:create username/api-name/XXX -f "/path/to/openapi.spec.json" --visibility=public --setdefault` (for a new one)
3. See error below
```
Created version XXX of API 'username/api-name'
    TypeError: Cannot read property 'split' of undefined
```

### Expected behavior
I expect the updated or created API to be set as the default

**Comment by barryadk** [comment]
Hi @dosaki,

I think the issue is related to the API argument `username/api-name/`.

It should be in the format:
`username/api-name`  - this refers to the default version of the API (so no change by setting it as the default again).
`username/api-name/version` - this is a specific version of the API.

Say you wanted to update the API definition of version `2.0.0`, and make it public & default, you would enter:
`swaggerhub api:update username/api-name/2.0.0 -f "/path/to/openapi.spec.json" --visibility=public --setdefault`

There are other examples available in the api:update help: `swaggerhub api:update -help`

**Comment by dosaki** [comment]
I must've edited out the version when making my post because my automated pipeline always includes the version.

I double-checked to ensure I was using the version in the argument and I am.
I've also just tried again and I am getting the same error.

**Comment by barryadk** [comment]
I'm able to reproduce the issue now. It affects the `setdefault` and `publish` flags when creating or updating an API. We'll aim to fix the issue in the next release, which should be early in the new year. Until then, the `api:setdefault` command can be used as a workaround. Thanks very much for raising the issue.
